#!/usr/bin/env python3
"""Create / update pages/tienda/<slug>/index.html for every active product in public/db/productos.json.

    python tools/generar-paginas-producto.py

The page itself is rendered by renderProduct() in js/tienda.jsx, which reads the JSON at load time, so price, stock
or description changes need no regeneration. Re-run only after adding a product or changing slug, name,
hero_ingredient, short, price_mxn or stock (copied into <head> and schema.org for search engines).
Product folders whose slug is no longer in the database are listed, not deleted.
"""
import html
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SITE = 'https://individuelgeneve.com.mx'
SHOP = ROOT / 'pages' / 'tienda'

TEMPLATE = """<!DOCTYPE html>
<html lang="es-MX">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{title}</title>
    <meta name="description" content="{description}">
    <link rel="canonical" href="{url}">
    <meta property="og:title" content="{title}">
    <meta property="og:description" content="{description}">
    <meta property="og:url" content="{url}">
    <meta property="og:type" content="product">
    <link rel="icon" href="/img/favicon.svg" type="image/svg+xml">
    <meta name="theme-color" content="#f4dfe2">
    <script type="application/ld+json">{jsonld}</script>

    <script src="https://cdn.tailwindcss.com"></script>
    <script src="/js/tailwind.config.js"></script>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Cormorant+Garamond:ital,wght@0,300;0,400;0,500;1,400&family=Jost:wght@300;400;500&family=Pinyon+Script&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="/css/site.css">

    <script crossorigin src="https://cdnjs.cloudflare.com/ajax/libs/react/18.2.0/umd/react.production.min.js"></script>
    <script crossorigin src="https://cdnjs.cloudflare.com/ajax/libs/react-dom/18.2.0/umd/react-dom.production.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/babel-standalone/7.23.5/babel.min.js"></script>
</head>
<body>

    <div id="root"></div>

    <script type="text/babel" src="/js/layout.jsx"></script>
    <script type="text/babel" src="/js/acceso.jsx"></script>
    <script type="text/babel" src="/js/tienda.jsx"></script>
    <script type="text/babel">
        // Generated by tools/generar-paginas-producto.py. The product is found from this page's URL.
        renderProduct();
    </script>
</body>
</html>
"""


def main():
    products = json.loads((ROOT / 'public' / 'db' / 'productos.json').read_text(encoding='utf-8'))['products']
    active = [p for p in products if p.get('active', True)]

    for p in active:
        url = f"{SITE}/pages/tienda/{p['slug']}/"
        title = f"{p['name']} · {p['hero_ingredient']} · Individuel Genève"
        jsonld = {
            '@context': 'https://schema.org', '@type': 'Product',
            'name': f"{p['name']} {p['hero_ingredient']}", 'sku': p['sku'], 'description': p['description'],
            'brand': {'@type': 'Brand', 'name': 'Individuel Genève'},
            'offers': {
                '@type': 'Offer', 'url': url, 'priceCurrency': 'MXN', 'price': p['price_mxn'],
                'availability': 'https://schema.org/' + ('InStock' if p['stock'] > 0 else 'OutOfStock'),
            },
        }
        out = SHOP / p['slug'] / 'index.html'
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(TEMPLATE.format(
            title=html.escape(title), description=html.escape(p['short'] + ' ' + p['description']), url=url,
            jsonld=json.dumps(jsonld, ensure_ascii=False).replace('</', '<\\/'),
        ), encoding='utf-8', newline='\n')
        print(f"ok   pages/tienda/{p['slug']}/")

    slugs = {p['slug'] for p in active}
    stale = [d.name for d in SHOP.iterdir() if d.is_dir() and d.name not in slugs]
    for name in stale:
        print(f"OJO  pages/tienda/{name}/ ya no está en la base de datos: bórrala y añade la ruta a MOVED en 404.html")


if __name__ == '__main__':
    main()
